- tensor2tensor/data_generators/text_encoder.py
I encountered a few small bugs when trying this out, these commits appear to fix both. The errors I encountered were:
- the `TokenTextEncoder` constructor choked when I provided it with a vocab filename, both in that it didn't read the file (which caused `id_to_token` to not be initialized), and the super class constructor was called after some code that relied on the `num_reserved_ids` property to be set.
- the `build_to_target_size` method on `SubwordTextEncoder` could invert min / max during the binary search if the target vocab size was larger than the actual vocab size, which triggered an infinite loop with min 1 / max -1. I'm not sure if this is the best fix (should it short circuit return if the source vocab is already smaller than the target?).
> Two small fixes

- tensor2tensor/data_generators/generator_utils.py
Hi,
this PR displays a progress bar during the download process as kind of indicator how long the download may take. As seen in #23 the download process can take several hours, especially  when downloading corpora from the `statmt.org` website.
> data-generators: show nice progress bar for download process

- tensor2tensor/utils/t2t_model.py
The class `modality.ClassLabelModality` does not appear to exist (any more?); this change makes inference work for me.
> fix broken reference in inference

- tensor2tensor/data_generators/wmt.py
- tensor2tensor/data_generators/wmt_test.py
This PR modifies `wmt.py` to use `text_encoder.ByteTextEncoder()` to **encode** source and target strings in its character based data generators. This synchronizes the behavior with `problem_hparams.py` which uses `text_encoder.ByteTextEncoder()` to **decode** inferred strings. Prior to this PR, encodes and decodes in character models are different and results therefore incorrect.
The PR also defines the constant `EOS` with the value 1 to avoid a "magic constant" appearing in the source code.
> Use ByteTextEncoding() for encoding strings in character based models

- tensor2tensor/utils/t2t_model.py
Hi, all
I used to post a issue "https://github.com/tensorflow/tensor2tensor/issues/43" that will occur an "index out of bound" error in decoding.
After I upgrade the tensor2tensor to 1.0.8, the problem still exists while happens in different place, but still when decoding.
After some investigation, I found it seemed that it only happened when the target modality is ClassLabelModality. 
I just made a quick fix to avoid this error index.  But I'm not a beam search expert and not aware of the potential problems.
After employing this fix, my decoding seems good for now. 
Would you please review this PR fix to see if it's ok. @lukaszkaiser 
Thanks a lot!
> Ask for a pull request to avoid "index out ouf bound" when doing prediction

- tensor2tensor/data_generators/generator_utils.py
- tensor2tensor/data_generators/snli.py
- tensor2tensor/data_generators/text_encoder.py
- tensor2tensor/data_generators/text_encoder_build_subword.py
- tensor2tensor/data_generators/tokenizer.py
This PR updates the Tokenizer and the SubwordTextEncoder to be Unicode-based instead of UTF-8 based.
This means that the full Unicode set of punctuation and separator characters is recognized when tokenizing the text, and that wordpieces are always formed at bone fide Unicode character boundaries. The former improvement helps to clean up the vocabulary and make it more efficient, since Unicode punctuation such as proper double quotes and em dashes is no longer seen as parts of words, while the latter avoids potential errors when wordpieces could start or end within UTF-8 multi-byte sequences denoting a single character.
The drawback is that it is not feasible to include the entire set of Unicode code points in the vocabulary (in contrast with including all code points 0..255 for UTF-8). …
> Unicode in SubwordTextEncoder

- tensor2tensor/utils/t2t_model.py
First of all, I apologize for the previous error that I misused the len operator.
Then I figure out if the beam is set to the value that's greater than 1 will still cause the Out of index error.
For Class_Label_Modality search , beam is set to 1 to enable greedy_infere seems to get better results.
@lukaszkaiser 
1. for beam search use the shape.ndims to avoid out of index error
2. for greedy search, still use the shape.ndims to avoid the out of index error. Before that I misuse the slice operation:-(
> I'm afraid I need to ask for pull request again for the "Out of index" Error when doing Class_Label_Modality

- tensor2tensor/data_generators/problem_hparams.py
If an incorrect value for `--problems` is specified to `t2t-trainer`, then the list of allowed values printed is sorted in arbitrary order, which is hard to read.
> Improve error message for missing problems

- setup.py
Hi,
with release *1.0.10* (see [Release page](https://github.com/tensorflow/tensor2tensor/releases)) the version number in `setup.py` was not updated.
So e.g. `pip` can't find the latest version:
```bash
pip install --upgrade "tensor2tensor==1.0.10"
Collecting tensor2tensor==1.0.10
Could not find a version that satisfies the requirement tensor2tensor==1.0.10 (from versions: 1.0, 1.0.1.dev1, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9)
No matching distribution found for tensor2tensor==1.0.10
```
This PR fixes it :)
> Bump to v1.0.10

- tensor2tensor/models/common_layers.py
- tensor2tensor/models/common_layers_test.py
Fix shape invariance issue by removing cond calls in _conv_internal()_ and _pool()_ functions in _common_layers.py_
To prevent _testConvGRU()_ from failing set middle two shapes to 'None' inside the LEFT padding condition. Also update _testConvStride2MultiStep()_ to prevent failure
> Fix issue 80: Crash with `algorithmic_multiplication_binary40` on `neural_gpu`

- tensor2tensor/models/common_layers.py
- tensor2tensor/models/lstm.py
- tensor2tensor/models/lstm_test.py
A new model called **baseline_lstm_seq2seq_attention** which will allow LSTM seq2seq to be used with attention. 
The main component is a cell wrapper called **ExternalAttentionCellWrapper** which is based on the [AttentionCellWrapper](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/AttentionCellWrapper) but takes attention states externally. The main reason for a cell wrapper is to allow usage with  `dynamic_rnn()`.  It can probably be faster but I wanted to get something out quickly.
I've also created a small hparams set for the attention model.
> Adding attention to LSTM seq2seq baseline

- tensor2tensor/models/common_layers.py
- tensor2tensor/utils/metrics.py
Update _pad_with_zeros()_ to return padded logits as well to handle cases where the logits sequence is shorter than the target sequence. Update corresponding calls.
> Fix issue 79: Mismatch in Logits and Labels

- setup.py
Bumps version information in `setup.py` to the latest *1.0.11* release (so that `pip` can find it).
> Bump to v1.0.11

- tensor2tensor/models/common_layers.py
- tensor2tensor/models/common_layers_test.py
- tensor2tensor/models/transformer_alternative.py
- tensor2tensor/models/transformer_alternative_.py
- tensor2tensor/models/transformer_test.py
Added the following layers (and tests):
*`global_pool_1d`: Not much to this, just a simple max/mean reduce across all vectors in a sequence. Useful for getting a single vector representation of a sequence/set. This can also be thought of as a kind of global attention.
* `linear_set_layer`: Simple 1d convolution across all elements in a sequence (similar layers are already used in repo), but also includes the ability to parameterise the transformation via with a (learned) sequence 'context' vector. Currently this is done by simply concatenating the inputs with the context.
*`ravanbakhsh_set_layer`: Layer type used in https://arxiv.org/abs/1611.04500.
These layers are permutation invariant and hence are suitable for applications where inputs are given as sets, but they may also be useful …
> Add new set network layer type and example model

- tensor2tensor/data_generators/text_encoder.py
- tensor2tensor/data_generators/wiki.py
use six.text_type or decode instead
> replace unicode in python3

- tensor2tensor/bin/t2t-datagen
- tensor2tensor/data_generators/problem_hparams.py
- tensor2tensor/data_generators/wmt.py
1. Following the `wmt_ende_token_32k` scheme, where we uses a separated vocabulary (No word segmentation. Please test it, because I found it performs very bad). Both source and target vocabulary contains about 32k words.
2. Using [wmt 2017](http://www.statmt.org/wmt17/translation-task.html) Chinese-English data. Only used `News Commentary v12` as training data, which contains only about 200,000 sentence pairs.
3. In the dev data, there's no plain text data available. We need to process the `sgm` file into plain text first.
> add wmt_zhen_token_32k

- tensor2tensor/models/common_hparams.py
- tensor2tensor/models/common_layers.py
- tensor2tensor/models/models.py
- tensor2tensor/models/shake_shake.py
- tensor2tensor/utils/trainer_utils.py
The model hasn't yet been tested empirically, but it's intended to match "Shake-Shake-Batch" of https://arxiv.org/pdf/1705.07485.pdf on CIFAR-10.
Some potential differences:
* tensor2tensor puts smaller weight decay on larger variables
* Input augmentation details likely differ slightly from fb.resnet.torch
* fb.resnet.torch probably doesn't use gradient clipping
* Different input and output flow. Shake-Shake uses 3x3 conv with 32 channels + batch norm, and 8x8 average pooling + FC, respectively.
> Add Shake-Shake model

- tensor2tensor/data_generators/generator_utils.py
- tensor2tensor/data_generators/problem.py
- tensor2tensor/data_generators/wmt.py
Hi,
this PR adds a new problem called `setimes_mken_tokens_32k`. It is now possible to build a neural machine translation system for Macedonian to English.
The [*SETimes*](http://nlp.ffzg.hr/resources/corpora/setimes/) corpus is used. It consists of 207,777 parallel sentences. The training set uses 205,777 sentences and the development set has a size of 1,000 sentences.
For a [test set](https://github.com/stefan-it/nmt-mk-en/blob/master/data/setimes.mk-en.test.tgz) with 1,000 sentences a BLEU-score of 47,49 (using Moses' `multi-bleu.perl`) can be achieved.
> Add new problem: Macedonian to English (SETimes corpus)

- tensor2tensor/bin/t2t-datagen
- tensor2tensor/bin/t2t-trainer
- tensor2tensor/utils/usr_dir.py
As described in issue #134 , it is now possible to add new problems by subclassing Problem and registering it, but there is no analogous mechanism to parameter `--t2t_usr_dir` from `t2t-trainer` which allows loading user-provided code. This PR simply consists in factoring out the functionality of `--t2t_usr_dir` out of `t2t-trainer` to a common place, and use it from both `t2t-trainer` and `t2t-datagen`.
> Support --t2t_usr_dir also in t2t-datagen

- tensor2tensor/data_generators/problem.py
- tensor2tensor/data_generators/problem_hparams.py
- tensor2tensor/data_generators/wmt.py
* simplify wmt.py:
`train_generator` is now a method (not a property returning a function)
and WMTProblem subclasses implement it directly (not via one-purpose functions)
* add WMT English-Czech translation problems
* introduce `vocab_name` property, so e.g. `tokens.vocab-en-cs.32768` is used instead of `tokens.vocab.32768` if only English+Czech datasets were used
> Simplify adding new translation language pairs

- tensor2tensor/utils/get_ende_bleu.sh
- tensor2tensor/utils/trainer_utils.py
Hi,
this PR removes the input sentence from the decoded file for `wmt_*` problems. 
It makes it harder for BLEU-score calculation when the input sentence is also shown. This was discussed in #112.
The example script for calculation the BLEU-score for a EN-DE system (`get_ende_bleu.sh`) is also updated with this PR.
> Remove input sentence from decoded file

- tensor2tensor/models/common_attention.py
This PR is to fix the positional embeddings in the [codes](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/common_attention.py#L29)
As mentioned in the paper, the positional embedding should be 
while in the code, it's calculated as 
Please check the differences.
> fix positional embedding

- tensor2tensor/utils/model_builder.py
Use six.iteritems(...) instead of losses_dict.iteritems()
> Fix Python3 support in model_builder.py

- tensor2tensor/utils/yellowfin.py
@lukaszkaiser as promised, i've updated YellowFin, now it works **but only** with TensorFlow 1.3.0.
The problems reside on the `Estimator` API or something related to it because i've retried the old version with TF v.1.3.0 and runs without any errors.
Unfortunately i cannot test it in a distributed environment. 
In all my experiment with T2T v.1.1.19, i've encountered the `CUDA_ERROR_OUT_OF_MEMORY` that i think it was introduced with the last PRs, because i've test the old optimizer with T2T v.1.1.13 and TF v.1.3.0 and i haven't any errors as said here #125  and here #213.
> Update YellowFin Optimizer

- tensor2tensor/utils/trainer_utils.py
I find these options quite useful.
E.g. when averaging the final model 20 30-minutes interval checkpoints are better
than 20 10-minutes interval checkpoints, according to my experiments.
> add options save_checkpoints_secs and keep_checkpoint_every_n_hours

- tensor2tensor/data_generators/text_encoder.py
The first [uses feature detection, instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection) and the second [avoids assigning a lambda expression to a variable](https://docs.quantifiedcode.com/python-anti-patterns/correctness/assigning_a_lambda_to_a_variable.html).
> Simplify native_to_unicode() & unicode_to_native()

- tensor2tensor/utils/diet_test.py
xrange() was removed in Python 3.  For counting to 10, `from six.moves import xrange` would be overkill.
> tensor2tensor: xrange(10) --> range(10) for Python 3

- tensor2tensor/utils/model_builder.py
Deletion of dict keys while iterating over said dict is a no-no in Python 3, and RuntimeErrors.  This simply consumes the dict key iterator into a list before iterative deletion.
> Fix key deletion during key iteration in Python 3

- tensor2tensor/utils/model_builder.py
Hi,
this PR fixes a spelling mistake for the diet variables logging message.
> model_builder: fix log message for diet variables

- tensor2tensor/visualization/TransformerVisualization.ipynb
raw file fix to be again readable by jupyter notebook : line 196 and 219
> * Fix ipynb file

- tensor2tensor/utils/input_fn_builder.py
- tensor2tensor/utils/input_fn_builder_test.py
See issue #311 
Since TF update: https://github.com/tensorflow/tensorflow/commit/3aaf220fef04c1ab71301c4fc76739c6a4df605e
multi-problem runs fail with crash inside `tensor2tensor.input_fn_builder.cond_on_index()`
Fixed by removing flattening trick (no longer needed). Added unit test.
> Fixes #311 - Multi-problem models do not work with recent TF

- tensor2tensor/data_generators/translate_enzh.py
@lukaszkaiser @martinpopel 
This is to close #315 #347 and #380 
Make sure this is correct.
But people can't expect good results with this toyset. I added a comment on this.
> Fix the EnZh task

- tensor2tensor/models/lstm.py
The LSTM Attention model was updated:
1. Replaced old attention model with `AttentionWrapper` based code
2. *HParams* added for Bahdanau Type Attention and Luong Type Attention
3. *HParams* added for multi-head attention
4. Set weight decay to 0 to fix NaN training loss issues
I did a quick comparison with the variants on the *translate_ende_wmt_bpe32k* task. 
After 2000 train steps:
| Model                                 | Parameters | Validation Loss  | BLEU | Accuracy |
| ----------------------------- | ------------- | -----------------|-------|-----------|
| LSTM Bahdanau Attention  | 14867456 | 6.25 | 0.2351 | 11.73% |
| LSTM Luong Attention        | 14850944  | 6.27 | 0.2319 | 11.72% |
| LSTM Bahdanau Attention Multi (4)  | 15228416 | 6.18 | 0.2370 | 11.99% |
| LSTM Luong Attention …
> Update LSTM Attention Model to use tf.contrib.seq2seq.AttentionWrapper

- tensor2tensor/utils/data_reader.py
Currently, the outputted `SavedModel` as decode server, the generated placeholder shape for tf.VarLenFeature will be a `[None]` int array. Then by intuition if we feed with a 1-Dim int array, the input will be transformed to a `[None, 1, 1, 1]` via `tf.expand_dims`. Then the only one int array input is treated as a batched int input, and everything else outputted form model will be crashed.
By adding one rank with undefined dim size to placeholder will fix this.
I tired `transformer`, `transformer_vae`, and `lstm`, all hit this problem, but not sure if all other models are the same. I am not fermilier with all other models and possiblly this change would break other models.
> 2-Dims placeholder for tf.VarLenFeature

- README.md
without this option `t2t-decoder` crashes, see #397
> add use_last_position_only=True

- tensor2tensor/bin/t2t-decoder
- tensor2tensor/utils/decoding.py
`--decode_to_file=xy` should use `xy` as the output filename,
not `xy.$MODEL.$HPARAMS.$PROBLEM.beam$BEAM_SIZE.alpha$ALPHA.decodes`.
It is easy for users to add whatever env variables to xy,
but it is impossible to change the hardwired suffix.
> fix the semantics of decode_to_file

- tensor2tensor/data_generators/cnn_dailymail.py
- tensor2tensor/utils/decoding.py
- tensor2tensor/utils/get_cnndm_rouge.sh
- tensor2tensor/utils/get_rouge.py
This commit adds the following features:
- Raw test data generation for the train, dev and test splits for the cnn/dailymail data. This allows for evaluating the performance of the model in a way that is comparable to other models
- A script to compute rouge scores using the official pyrouge distribution.
- Ensure that you have pyrouge setup on your machine correctly (Will add a pyrouge test script in the future)
- The script outputs warnings for empty model predictions. This is because the model did not generate a summary for that example. These were not suppressed since its a useful data point to have.
- A bash script that first runs the moses tokenizer on predictions and targets and then computes the rouge score using the aforementioned pyrouge based script.
- Just want to explicitly …
> Completing the CNN/Dailymail summarization pipeline

- tensor2tensor/bin/t2t-datagen
- tensor2tensor/data_generators/all_problems.py
- tensor2tensor/data_generators/librispeech.py
Added a generator for the librispeech datasets and included it in the supported generators in t2t-datagen.
Like the audio / TIMIT generator, this is dependent upon sox for WAV file generation.
> Added a librispeech data generator.

- tensor2tensor/layers/modalities.py
I assume this is what it was supposed to be.
> Extremely minor: spelling fix: 'fo' => 'to'

- docs/new_problem.md
`data_generators.wmt` seems to have become `data_generators.translate`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tensor2tensor/489)
> data_generators.wmt => data_generators.translate

- tensor2tensor/data_generators/generator_utils.py
- tensor2tensor/data_generators/translate_enzh.py
This PR adds full dataset to `TranslateEnzhWmt` if available. 
The UN parallel corpus, and CWMT corpus need to be downloaded from official website after registering. We add instructions to add the downloaded datasets manually to e.g. `/tmp/t2t_datagen/dataset.tgz` and add code to append to full training dataset if available. 
Fix #446 Added `file_size_budget` as argument to `get_or_generate_vocab`.
> Enhance WMT17 En-Zh task with full dataset.

- tensor2tensor/bin/t2t-avg-all
- tensor2tensor/bin/t2t-bleu
- tensor2tensor/bin/t2t-translate-all
- tensor2tensor/utils/bleu_hook.py
`t2t-bleu` computes the "real" BLEU
(giving the same result as [sacréBLEU](https://github.com/awslabs/sockeye/tree/master/contrib/sacrebleu) with `--tokenization intl`
and as [mteval-v14.pl](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v14.pl) with `--international-tokenization`).
It can be used in two ways:
* To evaluate one translated file: `t2t-bleu --translation=my-wmt13.de --reference=wmt13_deen.de`
* To evaluate all translations in a given directory (created e.g. by `t2t-translate-all`).
`t2t-translate-all` translates all checkpoints in a given directory (created by `t2t-trainer` or `t2t-avg-all`).
A custom command (e.g. SGE cluster wrapper) can be used instead of `t2t-decoder` for the translation.
`t2t-avg-all` for each checkpoint in a given …
> scripts for proper BLEU evaluation, batch translation and averaging

- tensor2tensor/models/transformer_vae.py
__xrange()__ was removed from Python 3 in favor of __range()__.
> from six.moves import xrange

- README.md
Many researchers are still reporting approx_bleu and comparing it with proper BLEU reported in other papers.
We should guide them to not do this and minimize the risk of false-news papers, such as https://arxiv.org/abs/1712.09662.
> Show t2t-bleu usage

- tensor2tensor/data_generators/translate_enmk.py
Hi,
*1.5.2* introduces some modifications in the `compile_data` function of the `translate` data generator. The `TranslateEnmkSetimes32k` problem uses a customized `source_data_files` function which was no longer compatible to the changes introduces in *1.5.2*. The leads to the following error:
```bash
File "/mnt/tensor2tensor/tensor2tensor/data_generators/translate.py", line 243, in compile_data                                                                       
lang1_filename, lang2_filename = dataset[1]                                     
ValueError: not enough values to unpack (expected 2, got 1) 
```
This PR fixes this problem :)
> enmk: fix dataset generation

- tensor2tensor/data_generators/text_problems.py
approx_vocab_size is treated as a property later on in the file in, for example, vocab_filename.
> Makes approx_vocab_size a property as was intended

- tensor2tensor/data_generators/text_encoder.py
If vocab.decode() make too big unicode point like "\u9876543;",  match() returns null string and tokenizer.decoder() raises "string index out of range" when accessing the first character of the null string.
This fix returns "\u3013" (used generally as undefined character) in such case.
> fix: avoid tokenizer error on too big unicode point

- tensor2tensor/data_generators/translate.py
One more approx_vocab_size that should be decorated with @property. All the rest of the
instances of approx_vocab_size have this decoration.
> Makes approx_vocab_size a property

- tensor2tensor/data_generators/generator_utils.py
By trying to copy files to the local, tmp-dir cache using tf.gfile.Copy before
using urllib2, origin files can now also be paths on a locally-mounted
filesystem or on GCS.
> Maybe_download can copy from filesystem or GCS

- tensor2tensor/data_generators/text_problems.py
In the text problem re-factor commit [`765d33`](https://github.com/tensorflow/tensor2tensor/commit/765d33bb6890cc7b8f194257d9c71226c26e0162) the behavior of the text iterator was changed in a way that it stops on the first empty line.
This breaks the ende translation, since the parallel corpus contains quite some empty lines and therefore was stopping after 235 lines of `news-commentary-v12.de-en.en`.
Here is a fix, which `strip()`'s only when yielding the result as it was in version `1.5.1`.
> fix txt_line_iterator to not stop at empty line

- tensor2tensor/data_generators/translate_enmk.py
Hi,
this PR adjusts the source and target language for the `TranslateEnmkSetimes32k` problem.
> enmk: use right order of source and target language

- tensor2tensor/data_generators/problem.py
When adding packed problems, it was forgotten to also reverse and/or copy the additional features `position`and `segmentation` for the `_rev` and `_copy` problems.
This PR adds the missing switches and copies.
> fix reverse/copy for packed problems

- tensor2tensor/data_generators/translate_envi.py
Hi,
with this PR a new problem is added: English-Vietnamese using the IWSLT'15 dataset from the [Stanford NLP group](https://nlp.stanford.edu/projects/nmt/).
I trained an English to Vietnamese model for 125k steps on a NVIDIA GTX 1060. Here are some nice comparisons of BLEU score on the `tst2013` test set. Other BLEU scores are taken from the [Towards Neural Phrase-based Machine Translation](https://arxiv.org/abs/1706.05565) paper.
| Model                                                                                                 | BLEU (Beam Search)
| ----------------------------------------------------------------------------------------------------- | ------------------
| [Luong & Manning (2015)](https://nlp.stanford.edu/pubs/luong-manning-iwslt15.pdf)                     | 23.30
| …
> en-vi: add IWSLT'15 English-Vietnamese as new problem

- tensor2tensor/data_generators/translate_enmk.py
Hi,
this PR adds the possibility for char-based NMT for English-Macedonian: `TranslateEnmkSetimesCharacters`.
BLEU-score for experiments I did with different `tensor2tensor` versions (all on DGX-1):
| Experiment | BLEU-score
| -------------- | ----------------
| Transformer (1.1.0) | 52,70
| Transformer - character-based (1.1.0) | 34,26
| Transformer (1.5.2) | 54,00 (uncased)
| Transformer - character-based (1.5.2) | 37.43 (uncased)
> en-mk: add new character-based problem

- .github/ISSUE_TEMPLATE.md
Hi,
this PR introduce an issue template for GitHub.
In the "write" mode of an issue, various useful hints are shown:
I merged this PR into my forked repository, so you can play around with the issue template. See it [here](https://github.com/stefan-it/tensor2tensor/issues/new).
Please let me know if we need to include more information :)
> WIP: github: add initial issue template

- tensor2tensor/data_generators/imagenet.py
- tensor2tensor/layers/common_layers.py
- tensor2tensor/layers/modalities.py
Fixed the use of name_scope by passing the `values` argument as a named argument wherever it is used. This should fix #615.
> Fixed use of name_scope by using named arguments whenever needed

- tensor2tensor/data_generators/ptb.py
Fixes PTB data generator, which seemed to get overlooked in a recent refactor.
* Adds `is_generate_per_split` property.
* Downloads corpus before returning generator in generate_samples. This is because `Text2TextProblem`'s `generate_encoded_samples` method expects a generator to be returned from `generate_samples`, but for `TOKEN` vocabularies the file must already exist before `get_or_create_vocab` is called (https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/text_problems.py#L222).
* Moves code to download corpus out of generate_samples method (seemed a bit clearer).
> Fix PTB data generator.

- tensor2tensor/bin/t2t_trainer.py
Allows `hparams.json` file include hparams added by the problems.
> Move save_metadata function down to after create exp_fn

- tensor2tensor/models/transformer.py
This pull request is to fix the issue "https://github.com/tensorflow/tensor2tensor/issues/649" .
When the transformer is trained as a language model, the input is set to partial_targets. But the shape doesn't contain the fourth dimension.
After testing with my own dataset, the problem is fixed by this modified code.
> Fix the language model predition shape error.

- docs/cloud_mlengine.md
- tensor2tensor/utils/cloud_mlengine.py
This fixes the following issues:
- A typo in FLAGS which was looking for `cloud_ml_engine_master_type` rather than `cloud_mlengine_master_type`. 
- An error being raised based on API client dependency versions (see https://github.com/google/google-api-python-client/issues/299)
- Some clarification in the docs when using non-GPU workers.
> Fixed small issues with ML Engine script.

- tensor2tensor/data_generators/text_encoder.py
- tensor2tensor/models/transformer.py
1. For the ClassLabelEncoder, it's derived from TextEncoder and didn't implement decode_list, so it didn't not produce correct labels when passing a list of class ids.
2. For transformer, if the problem is a language model, it didn't return the correct beam size when doing the beam search. This fix will ensure the beam search produce the correct the search results for problems with no "input", a.k.a language model.
> Fix two bugs : 1. Add decode_list in ClassLabelEncoder, 2. Fix the bug for language model problem's beam search

- tensor2tensor/models/transformer.py
Note that _beam_decode_slow should not be wrapped in variable_scope(name)
unlike _fast_decode which must be wrapped so.
Fixes #674 and allows to decode with transformer_relative.
This PR is an substitute for #675 (same, but rebased on v1.5.5).
> Fix transformer decoding when using attention other than dot_product.

- README.md
- docs/index.md
- docs/walkthrough.md
Hi,
this PR adds the English-Vietnamese problem to all relevant translation sections in the `tensor2tensor` documentation.
> documentation: add English-Vietnamese problem

- tensor2tensor/bin/t2t_decoder.py
- tensor2tensor/bin/t2t_trainer.py
- tensor2tensor/utils/decoding.py
1. fix bug: t2t-decoder must specify checkpoint_path introduced in commit `111129e44df589f2ee688e0e4abef12d6d16955f`
2. add support for only specifying checkpoint_path in t2t-decoder interactive mode
> add support for specifying checkpoint_path in t2t-decoder interactive mode

- README.md
- docs/walkthrough.md
Hi,
this PR includes a minor fixes for the link to the distributed training documentation (in main readme file and in walkthrough doc).
> readme: fix link to distributed training documentation

- tensor2tensor/utils/bleu_hook.py
The evaluation using t2t-bleu failing using Python 3.5.4. The issue is due to deletion of the "encoding='utf-8'" tag in the previous version of `bleu_hook.py' file for support Python2. Please refer to bug #706 for details.
> To fix the BLEU Evaluation Error #706

- tensor2tensor/utils/cloud_mlengine.py
The tensor2tensor.utils.cloud_tpu (or cloud in this file) library's methods typically return byte strings and not strings, however cloud_mlengine.py mostly treats the results as strings.
An alternative change might be to use decode here instead: https://github.com/tensorflow/tensor2tensor/blob/120315cbe35f468876512b790dc77d792d4db72c/tensor2tensor/utils/cloud_tpu.py#L219 (Note that check_output returns a byte string: https://docs.python.org/2/library/subprocess.html)
Example error when attempting to run t2t-trainer:
TypeError: b'' is not JSON serializable
> Decode bytes into string when getting cloud 

- tensor2tensor/bin/t2t_trainer.py
- tensor2tensor/utils/trainer_lib.py
This PR is to enable passing inter_op_parallelism_threads and intra_op_parallelism_threads as command line args. Setting these arguments correctly improves ASR (librispeech_transformer) model performance on CPU considerably.
> Enabling setting Tensorflow inter_op and intra_op

- tensor2tensor/__init__.py
- tensor2tensor/bin/__init__.py
- tensor2tensor/data_generators/__init__.py
- tensor2tensor/insights/__init__.py
- tensor2tensor/layers/__init__.py
- tensor2tensor/layers/common_attention.py
- tensor2tensor/models/research/__init__.py
- tensor2tensor/models/research/lm_experiments.py
- tensor2tensor/rl/__init__.py
- tensor2tensor/rl/envs/__init__.py
- tensor2tensor/serving/__init__.py
- tensor2tensor/utils/__init__.py
- tensor2tensor/visualization/__init__.py
Hi,
this PR applies some fixes recommended by `pylint`: 
* [W0404 (Used when a module is reimported multiple times)](https://github.com/PyCQA/pylint/blob/df1abe8d275970dbaefd2ccc4c22ad1c83eb381c/pylint/checkers/imports.py#L214)
* [C0305 (Used when there are trailing blank lines in a file)](https://github.com/PyCQA/pylint/blob/7fea701175aeefb0ab6f8613501f739a91671b3a/pylint/checkers/format.py#L93)
> Minor pylint fixes

- tensor2tensor/data_generators/README.md
Hi,
the `data_generator` readme file points to an already removed unit test (`wmt_test.py`), introduced with eacde9d9f5b4dede91bb95d4c38083bc70824b30. This PR updates the documentation for that.
> Fix link to unit tests for translation problems

- tensor2tensor/data_generators/all_problems.py
- tensor2tensor/data_generators/translate_enet.py
Hi,
this PR adds English-Estonian as new problem. English-Estonian is new for [WMT18](http://www.statmt.org/wmt18/translation-task.html), so all training data from WMT site is used.
The development data is also taken from WMT. Unfortunately, the original development data includes SGML tags, so I stripped them using [`input-from-sgm.perl`](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/ems/support/input-from-sgm.perl) from Moses.
> Add English-Estonian (WMT2018) as new problem

- tensor2tensor/data_generators/gym.py
- tensor2tensor/rl/envs/simulated_batch_env.py
- tensor2tensor/rl/envs/utils.py
- tensor2tensor/rl/model_rl_experiment.py
First we add freeway, but more can be added easily.
> Add more tari games.

- tensor2tensor/utils/t2t_model.py
If top_beams > 1 (return_beams=True) only the first word of every beam was returned. Bug introduced with last change of this line.
> Fix bug if top_beams > 1

- tensor2tensor/rl/collect.py
- tensor2tensor/rl/model_rl_experiment.py
- tensor2tensor/rl/rl_trainer_lib.py
For now:
* ppo_time_limit hparameter is unused
* ppo_epoch_length * 4 is the biggest number of steps in the simulated
enviroment during PPO. Thus this value should be set reasonably (and
not large). Batch size can be compensated by increasing ppo_num_agents.
> A hacky way of fixing value function computation.

- tensor2tensor/data_generators/all_problems.py
- tensor2tensor/data_generators/translate_enid.py
Add parallel corpora for English-Indonesian tasks. The sentences have been tokenized by using [SentencePiece](https://github.com/google/sentencepiece). Please refer to the following links for citation and the raw corpora.
[IWSLT17](https://wit3.fbk.eu/mt.php?release=2017-01-more) :
- train : 109335 sentences
- test : 1478 sentences
[PANL-BPPT](http://www.panl10n.net/english/OutputsIndonesia2.htm) : 24024 sentences
> Add English-Indonesian

- tensor2tensor/utils/learning_rate.py
When training with ```learning_rate_schedule=constant```, ```learning_rate``` is float type and would be wrapped as TF Variable by TensorFlow at [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/optimizers.py#L179), thus to be saved at checkpoint. However, when training with ```learning_rate_schedule= rsqrt_decay``` and other schedule mechanism(non-constant), ```learning_rate``` would be normal Tensor rather than Variable, and will not be saved at checkpoint, that leads error like #809 .
As it's not necessary to save ```learning_rate``` at checkpoint file, we can restore it from ```global_step``` and learning rate schedule which are set by hparams.
This PR wrap ```learning_rate``` as Tensor for both constant and non-constant values, then …
> Wrap constant learning rate as Tensor

- tensor2tensor/data_generators/cifar.py
Hi everyone!
with `Python 3.6.5` the following exception will be thrown, when using the `tensor2tensor.data_generators.cifar.cifar_generator`: 
```
File "/home/lhlmgr/anaconda3/lib/python3.6/site-packages/tensor2tensor/data_generators/cifar.py", line 146, in cifar_generator
data = cPickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```
Adding the the parameter `encoding='latin1'` to `cPickle.load` fixes this error for the `cifar10` and `cifar100` (`/cifar20`) datasets.
However, I haven't tested the code with python 2.7..
(btw. thanks for your great work!)
> Python 3.6.5: UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

- .travis.yml
Use [flake8](http://flake8.pycqa.org) to look for Python syntax errors or undefined names on both Python 2 and Python 3.
__E901,E999,F821,F822,F823__ are the "showstopper" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc.  Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.  This PR therefore recommends a flake8 run of these tests on the entire codebase.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable `name` referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree
> Travis CI: Python syntax errors or undefined names

- tensor2tensor/models/research/universal_transformer_util.py
__xrange()__ was removed in Python 3 in favor of __range()__ so convert all instances of __xrange()__ to __six.moves.range()__ for compatibility across Python 2 and Python 3.
Discovered via #942 at https://travis-ci.org/tensorflow/tensor2tensor/jobs/404819029#L1509
> from six.moves import range for Python 3

- tensor2tensor/data_generators/problem.py
- tensor2tensor/models/transformer.py
1. Adds problem transformer_timeseries_tpu to problem.py
2. Fix error "unexpected keyword argument drop_remainder" for running transformer model on TPU
> Create problem transformer_timeseries_tpu and fix error "unexpected keyword argument 'drop_remainder' on TPU

- tensor2tensor/data_generators/common_voice.py
Fixed bug in Common Voice problem 
Added specific conditional expression for Python 3.
Used the built-in function next in python 3:  next(reader) instead of reader.next() 
...
```
tensor2tensor==1.8.0
tensorboard==1.10.0
tensorflow==1.10.1
Python 3.6.5
```
```
1. Run datagen script for Common Voice problem (Python 3).
```
```
tensor2tensor/tensor2tensor/data_generators/common_voice.py", line 59, in _collect_data
_ = transcript_reader.next()  # Skip headers.
AttributeError: '_csv.reader' object has no attribute 'next'
```
> bug fix for python 3 in Common Voice problem

- tensor2tensor/models/research/universal_transformer.py
- tensor2tensor/models/research/universal_transformer_util.py
There are variants of the UT in which a gru or an lstm, flipped vertically, controls the flow of information in depth (i.e. a gru/an lstm as transition function instead of a ffn or sepconv). 
I cleaned up the code for these two variants also cleaned up some of the hparams_sets.
p.s. 
1. These changes are not relevant to the models described or results reported in the paper.
2. Sorry that the PR is rather large! Let me know if should break it into multiple PRs.
> Cleaning up the codes for gru/lstm as transition function for universal transformer

- tensor2tensor/data_generators/cnn_dailymail.py
When a basic `t2t-trainer` command is run with the `--problem=summarize_cnn_dailymail32k` command, the following error occurs:
```
UnicodeEncodeError: 'ascii' codec can't encode character '\xbb' in position 1426: ordinal not in range(128)
```
This minor fix resolves this issue.
Fixes issue #1068
> Avoid a ascii codec error in CNN/DailyMail.

- tensor2tensor/layers/common_attention.py
Tensors with less than 4 `channels` will get **NaN** in positional encodings.
> Avoid NaN while adding sinusoidal timing signals

- docs/new_problem.md
Just a minor change! Main purpose is to remove a reference to `word2def`, a file that's not actually in the tutorial. The rest is just small ease-of-reading fixes: I adjust a typo before the code snippet, and match tenses after the snippet.
> Updating new_problem.md to correct file names and simpler wording

- tensor2tensor/bin/t2t_trainer.py
- tensor2tensor/utils/trainer_lib.py
The patch allows user to specify which protocol to be used for distributed training. This enables the use of custom communication protocols (e.g. VERBS)
> Allow specifying which protocol to be used in tf.train.Server

- tensor2tensor/models/__init__.py
For consistency, since we can write
```python
from tensor2tensor import problems
problem = problems.problem('my_problem')
```
this should work for the module `models` too:
```python
from tensor2tensor import models
model = models.model('my_model')
```
> Expose method model() to load a model from registry

- tensor2tensor/data_generators/gym_problems.py
- tensor2tensor/data_generators/gym_problems_specs.py
- tensor2tensor/models/research/autoencoders.py
- tensor2tensor/models/video/basic_deterministic_params.py
- tensor2tensor/rl/envs/tf_atari_wrappers.py
- tensor2tensor/rl/trainer_model_based.py
- tensor2tensor/rl/trainer_model_based_ae_test.py
Speed up autoencoder test (in model-based rl pipeline). Enable passing autoencoder hparams by flags; dynamically construct autoencoder related problems; autoencoder wrappers are constructed with hparams_set.
> Speed up autoencoder test

- tensor2tensor/data_generators/gym_env.py
- tensor2tensor/data_generators/gym_env_test.py
- tensor2tensor/rl/trainer_model_based.py
T2TEnv: Full history cleaning on new epoch (fix); read only rollouts with size appropriate for initial_frame_chooser; initial_frame_chooser fix for simulation_random_starts case (unused so far);
Full cleaning of history in T2TGymEnv resolves bug with short rollout in initial_frames, but in the principle these kind of rollouts might be produced by environment anyway, so explicit filtering is also applied.
Moving indentation in change_initial_frames fixes potential bug which have not appeared yet (case "not environment_spec.simulation_random_starts" is not used currently)
> Model-Based RL: Fix short rollouts in initial_frames_number

- tensor2tensor/utils/t2t_model.py
- tensor2tensor/utils/trainer_lib.py
This might make my previously proposed PR https://github.com/tensorflow/tensor2tensor/pull/1154 obsolete.
In `trainer_lib.py`, the `train_hooks()` and `eval_hooks()` of the `T2TModel` are getting called. These are `static` methods which means we cannot access the `self` reference and further not the model's `hparams`. Therefore, any hook created in `train_hooks()` or `eval_hooks()` is lacking context information. At least until now I was not able to find an obvious way to retrieve additional required information for my hooks. For more context, `train_hooks()` and `eval_hooks()` should provide a `hook_context` object. 
The (arguably) simplest way at this point would be to pass a `hook_context` in `trainer_lib.py`. So instead of
```python
train_hooks += …
```
> Passing hook context to train and eval hooks

- tensor2tensor/utils/avg_checkpoints.py
During training, you might need to run avg_checkpoints a couple of times and generate different checkpoints. In that case, you need to reuse the variables you've made in the previous session calls.
> variable_scope wrapper for avg_checkpoints

- tensor2tensor/data_generators/common_voice.py
- tensor2tensor/data_generators/librispeech.py
The reason is that we cannot do this at the moment:
```python
class LibrispeechMod(Librispeech):
def feature_encoders(self, data_dir):
return {
'targets': MyCustomEncoder(data_dir)
}
```
because at the moment `feature_encoders()` is getting called by passing `None` (see [Librispeech](https://github.com/tensorflow/tensor2tensor/blob/v1.9.0/tensor2tensor/data_generators/librispeech.py#L140) and [CommonVoice](https://github.com/tensorflow/tensor2tensor/blob/v1.9.0/tensor2tensor/data_generators/common_voice.py#L136))
```python
def generator_(self, data_dir, tmp_dir, datasets, eos_list=None, start_from=0, how_many=0):
encoders = self.feature_encoders(None)
audio_encoder = encoders["waveforms"]
text_encoder = encoders["targets"]
```
> Pass data_dir to feature_encoders

- tensor2tensor/utils/trainer_lib.py
t2t-trainer passes problem_name=None to create_hparams(), and
adds the problem hparams afterwards when creating the experiment.
t2t-decoder instead relies fully on create_hparams()
This inconsistency causes t2t-trainer and t2t-decoder to pass
different sets of model_hparams to Problem.hparams() (before and
after overrides respectively), which is problematic.
Always letting the problem see the final version of the model
hparams is more useful (in case the problem hparams depend on
the model), so make sure the problem is added after the overrides.
> trainer_lib: add problem hparams after parsing the overrides

- tensor2tensor/models/research/universal_transformer.py
fixes issue discussed in https://github.com/tensorflow/tensor2tensor/issues/1191
> Fixes Universal Transformer not converging bug

- tensor2tensor/models/research/universal_transformer.py
- tensor2tensor/models/research/universal_transformer_util.py
Set the default for "use_memory_as_final_state" flag to False.
Removed the undefined/reduntant flag "use_memory_as_last_state".
NOTE: PR #1192 submitted by @rllin-fathom is basically addressing the same issue, but here I also added the condition of using memory as the final state only when the transition function is an LSTM (to avoid unintentional use of memory for other transition functions).
> Fixes UT convergence problem  (issue discussed in #1191)

- tensor2tensor/layers/modalities.py
Changed reuse val from true to tf.AUTO_REUSE in top to allow for proper weight initialization
> Fixing weight initialization in symbols modality

- tensor2tensor/rl/trainer_model_based.py
- tensor2tensor/rl/trainer_model_based_params.py
Removal of redundant filtering of not finished trajectories. (discussed with original code author) (6b18f44)
Split hparams to ones depending on rl algorithm (ppo/dqn) and not. This is needed because each time someone chages something in tiny or base set (e.g. adds new parameter) errors happen for dqn runs (not pushed to master yet).
> Model-Based RL: Split hparams dependent/indepent of RL algorithm (ppo/dqn)

- tensor2tensor/insights/README.md
- tensor2tensor/insights/polymer/explore_view/explore-view.html
- tensor2tensor/insights/server.py
Fixed a couple of errors in t2t-insights-server. The configuration example in README.md, missing d3 error and json serialization error.
> Couple of t2t-insights-server fixes

- tensor2tensor/models/research/universal_transformer_util.py
I found and fixed small bugs in UT implements in special case `length=1` for `universal_transformer_util.py`.
Addition to that, I fixed an operation by having some codes out of loop which looks meaningless iteration (this is not main).
I found bugs on a special case in `universal_transformer_util.py`:
- squeeze operations in `ut_function` without axis make the dimensions unknown and fail successive operation
- [L1136](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/research/universal_transformer_util.py#L1136), [L1288](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/research/universal_transformer_util.py#L1288)
The flow for L1136 is below:
1.  the dimensions of state is `[batch_size, length, channel]` as mentioned in comment at …
> [UT] small bugs in ut_function when one uses data length = 1

- README.md
- tensor2tensor/data_generators/babi_qa.py
1. Fixed bAbi data generator so it can now download data. 
2. Added instructions for bAbi data generation in readme.
> Fix bAbi data generator and readme

- tensor2tensor/data_generators/mrpc.py
Fixes #1246
- Fixed broken link to `mrpc_dev_ids.tsv`
> Fix broken MRPC download link

- tensor2tensor/data_generators/speech_recognition.py
- tensor2tensor/utils/metrics.py
- tensor2tensor/utils/metrics_test.py
Proposing an additional metric: Word Error Rate
- Adds `word_error_rate` in `tensor2tensor/utils/metrics.py`
- Unit test in `tensor2tensor/utils/metrics_test.py`
- Adds WER to `SpeechRecognitionProblem` `tensor2tensor/data_generators/speech_recognition.py`
> Word Error Rate for Speech Recognition

- tensor2tensor/models/research/vqa_self_attention.py
__xrange()__ was removed in Python 3 in favor of a revamped version of __range()__.  This PR proposes adding [__from six.moves import xrange__](https://six.readthedocs.io/#module-six.moves) to ensure equivalent functionality on both Python 2 and Python 3 and to avoid the potential of NameError being raised at runtime on Python 3.
[flake8](http://flake8.pycqa.org) testing of https://github.com/tensorflow/tensor2tensor on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tensor2tensor/models/research/vqa_self_attention.py:658:12: F821 undefined name 'xrange'
for _ in xrange(hparams.num_rec_steps):
^
1    F821 undefined name 'xrange'
1
```
> Undefined name: xrange() was removed in Python 3

- tensor2tensor/bin/t2t_avg_all.py
Currently `t2t-avg-all` creates an average of the `train_stats/problem_0_steps` variable, of type float32, which prevents restoring variables from the averaged checkpoints. This fix will create a dummy `train_stats/problem_0_steps` variable, of type int32.
> Fix problem_0_steps in checkpoint averages

- tensor2tensor/utils/metrics.py
- tensor2tensor/utils/metrics_test.py
Dear community, I'm using tensor2tensor for text similarity tasks and I find no metrics for calculating pearson correlation coefficient.
> add a metrics for calculating pearson correlation coefficient

- tensor2tensor/models/text_cnn.py
I'd like to add textCNN model for text classification problem.
* It's my first time to add new model to tensor2tensor, so please feel free to let me know if you have any concerns.
* Most code in this PR comes from [this repo](https://github.com/dennybritz/cnn-text-classification-tf), I just did some adaptation work to follow tensor2tensor interface, again please let me know if you have any concerns. @dennybritz
* I've done some experiments based on existing problem(sentiment_imdb), see below table in detail, again please let me know if we need more experiment result to add such model.
Problem | Model | Parameters | Metrics
-- | -- | -- | --
sentiment_imdb | transformer_encoder | hparam = transformer_tiny, train_steps = 2000 | accuracy=0.7675
sentiment_imdb | transformer_encoder | hparam = …
> add text CNN model for text classification problem

- tensor2tensor/data_generators/mrpc.py
Fixes #1280 
- Exclude dev data from training dataset of MRPC
- Add MRPC test dataset
- Training: 8152
- Dev: 816
- Test: 0
- Training: 7336
- Dev: 816
- Test: 3450
> MRPC: Exclude dev data from training dataset

- tensor2tensor/layers/common_attention.py
- tensor2tensor/models/transformer.py
Add Fast Decoding  Support For And Only For Relative Dot Product by enabling caching mechanism.
This pr have been tested on "En-Zh" case and got the same results as expected.
> Add Fast Decoding  Support For Relative Dot Product

- tensor2tensor/data_generators/problem.py
- tensor2tensor/utils/t2t_model.py
This PR lets custom evaluation stage hooks to be defined at the problem level.
> Custom eval hooks

- tensor2tensor/utils/devices.py
- tensor2tensor/utils/metrics.py
- tensor2tensor/utils/registry.py
- tensor2tensor/utils/t2t_model.py
[`inspect.getargspec`](https://docs.python.org/3/library/inspect.html#inspect.getargspec) is deprecated since Python 3.0. ~This PR replaces it's usage with `getfullargspec` to get rid of deprecation warnings.~ This PR replaces it's usage with [`tf_inspect`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/tf_inspect.py) to remove the warnings.
Fixes #1294 after https://github.com/tensorflow/tensorflow/pull/22517 is shipped.
> Remove deprecated calls to inspect.getargspec

- tensor2tensor/data_generators/translate.py
`is_generate_per_split` in TranslateProblem inherits from Text2TextProblem, so it should be set to property. Otherwise when we train model of TranslateProblem, the judgement in https://github.com/tensorflow/tensor2tensor/blob/65f66e70a1b145398e2df3c35f5af5fb135c7467/tensor2tensor/data_generators/text_problems.py#L302 will always be true (self.is_generate_per_split returns a method object), even if we overwrite `is_generate_per_split` (without `@property`) to return `False` in the subclass of TranslateProblem.
> Fix bug: "is_generate_per_split" should be set to property.

- tensor2tensor/data_generators/cnn_dailymail.py
- tensor2tensor/data_generators/cola.py
- tensor2tensor/data_generators/mrpc.py
- tensor2tensor/data_generators/multinli.py
- tensor2tensor/data_generators/qnli.py
- tensor2tensor/data_generators/quora_qpairs.py
- tensor2tensor/data_generators/rte.py
- tensor2tensor/data_generators/scitail.py
- tensor2tensor/data_generators/sst_binary.py
- tensor2tensor/data_generators/stanford_nli.py
- tensor2tensor/data_generators/text_encoder.py
- tensor2tensor/data_generators/wiki_revision_utils.py
- tensor2tensor/data_generators/wnli.py
__tensor2tensor.data_generators__ currently has two _different_ versions of __to_unicode()__, one in [__text_encoder.py__](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/text_encoder.py#L90-L94) and the other in [__wiki_revision_utils.py__](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/wiki_revision_utils.py#L38-L39).  This PR proposes renaming the second version --> __to_unicode_utf8()__ and moving it into __text_encoder.py__ with the other Unicode utility functions.
> Add to_unicode_utf8() to text_encoder.py

- tensor2tensor/data_generators/text_encoder.py
https://six.readthedocs.io/#six.text_type
> Simplify is_unicode()

- tensor2tensor/layers/common_attention.py
- tensor2tensor/models/transformer.py
- tensor2tensor/visualization/visualization.py
Hi, I've got some  further works on `dot_product_relative` here.
This PR enables visualization of `self-attention` and `encdec-attention` when using `dot_product_relative` as `self-attention` type
> Enable Relative Dot Product Visualization

- tensor2tensor/layers/common_layers_test.py
- tensor2tensor/layers/modalities_test.py
- tensor2tensor/models/basic_test.py
- tensor2tensor/models/bytenet_test.py
- tensor2tensor/models/image_transformer_2d_test.py
- tensor2tensor/models/image_transformer_test.py
- tensor2tensor/models/lstm_test.py
- tensor2tensor/models/mtf_image_transformer_test.py
- tensor2tensor/models/mtf_transformer_test.py
- tensor2tensor/models/neural_gpu_test.py
- tensor2tensor/models/research/autoencoders_test.py
- tensor2tensor/models/research/gene_expression_test.py
- tensor2tensor/models/research/transformer_aux_test.py
- tensor2tensor/models/research/transformer_revnet_test.py
- tensor2tensor/models/research/transformer_vae_test.py
- tensor2tensor/models/research/universal_transformer_test.py
- tensor2tensor/models/research/vqa_attention_test.py
- tensor2tensor/models/resnet_test.py
- tensor2tensor/models/slicenet_test.py
- tensor2tensor/models/transformer_test.py
- tensor2tensor/models/xception_test.py
[`np.random.random_integers`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random_integers.html) is deprecated in favor of [`np.random.randint`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html#numpy.random.randint) since numpy version 1.10.
This PR replaces calls to  `np.random.random_integers` with `np.random.randint`.
> Replace deprecated np.random.random_integers with np.random.randint

- tensor2tensor/utils/cloud_mlengine.py
`tensor2tensor` requires [`tensorflow>=1.12.0`](https://github.com/tensorflow/tensor2tensor/blob/master/setup.py#L59).
This PR upgrades the version on Cloud ML to 1.12 in order to fix run time errors.
Fixes #1234
Note: I only tested this change on Cloud ML *without* a TPU.
> Upgrade Cloud ML version to tf@1.12

- tensor2tensor/utils/t2t_model.py
Fixes #1002 as the current code will raise ___NameError: name 'loss' is not defined___ at runtime.
```
python -c '[{"training": l} for l in loss for loss in "this is a test".split()]'    # error
python -c '[({"training": l} for l in loss) for loss in "this is a test".split()]'  # works
```
> Fix invalid list comprehension

- tensor2tensor/layers/common_attention.py
- tensor2tensor/models/transformer.py
If `ffn_layer` is in `["dense_relu_dense" or "conv_hidden_relu"]`, than the cache "f" won't be used
which means that the` shape of cache["f"]` won't be changed to `[beamsize*batch_size, decode_length, hparams.hidden_size]` and may cause error when applying `nest.map reshape function` on it.
This only happened in eager_execution mode because this part of graph may not be execute in  non-eager_execution mode.
> Avoid error in beam search when "f" is in cache

- tensor2tensor/layers/latent_layers.py
- tensor2tensor/models/research/transformer_nat.py
- tensor2tensor/models/research/transformer_vae.py
- tensor2tensor/models/transformer.py
- tensor2tensor/utils/beam_search.py
- tensor2tensor/utils/beam_search_test.py
- tensor2tensor/utils/t2t_model.py
Some models, eg. semantic parsing models with copying mechanisms,
want to use the output of Transformer for multiple predictions.
One way to do so is to modify the symbols_to_logits_fn to generate
the additional predictions and save them in the cache dictionary.
To do so, though, fast_decode() must allow an externally supplied cache,
and must return it to the caller after the loop.
> transformer_fast_decode, beam search: take an optional cache and return it

- tensor2tensor/layers/common_layers.py
- tensor2tensor/layers/common_layers_test.py
- tensor2tensor/models/research/rl.py
- tensor2tensor/models/research/transformer_vae.py
- tensor2tensor/models/revnet.py
- tensor2tensor/models/video/base.py
- tensor2tensor/models/video/basic_deterministic.py
- tensor2tensor/models/video/basic_recurrent.py
- tensor2tensor/models/video/emily.py
- tensor2tensor/models/video/sv2p.py
- tensor2tensor/models/video/svg_lp.py
- tensor2tensor/utils/optimize.py
This PR replaces `tf.contrib.layers` with their stable `tf.layers` and `tf.initializers` equivalents.
> Reduce usage of tf.contrib.layers

- tensor2tensor/utils/cloud_mlengine.py
Cloud ML Engine can use [labels](
https://cloud.google.com/ml-engine/docs/tensorflow/resource-labels) to organize and filter jobs.
This PR adds labels for `model`, `problem` and `hparams_set`.
> Add labels to ml-engine job

- tensor2tensor/utils/cloud_mlengine.py
The `.git` directory isn't used on Cloud ML Engine, therefor we should ignore it in the uploaded archive.
This reduces the size of the `.tar.gz` archive from a fresh clone of `tensor2tensor` from 15 MB to only 3.6 MB.
> Exclude .git directory when submitting to Cloud ML Engine

- tensor2tensor/models/research/universal_transformer.py
- tensor2tensor/models/research/universal_transformer_util.py
Here I propose for the Universal Transformer with ACT with different `act_type`s to be combined into a single function to be more understandable. I believe that the proposed backwards-compatible change would benefit future variants.
> Combine AUT variants into a single function and define mix_with_transformer

- tensor2tensor/utils/cloud_mlengine.py
Currently the ML Engine jobs spec is hard to read. This PR formats the job spec for better readability.
```
INFO:tensorflow:Launching job shake_shake_image_mnist_t2t_20190113_170945 with ML Engine spec:
{'jobId': 'shake_shake_image_mnist_t2t_20190113_170945',
'labels': {'hparams': 'shake_shake_quick',
'model': 'shake_shake',
'problem': 'image_mnist'},
'trainingInput': {'args': ['--disable_ffmpeg=False',
'--timit_paths=',
'--wiki_revision_num_train_shards=50',
'--wiki_revision_num_dev_shards=1',
'--wiki_revision_data_prefix=',
'--wiki_revision_vocab_file=',
'--wiki_revision_max_examples_per_shard=0',
'--wiki_revision_max_page_size_exp=26',
'--wiki_revision_max_equal_to_diff_ratio=0.0',
'--wiki_revision_revision_skip_factor=1.5',
'--wiki_revision_percent_identical_examples=0.04', …
```
> Pretty print Cloud ML Engine job spec

- tensor2tensor/layers/common_attention.py
- tensor2tensor/layers/common_hparams.py
- tensor2tensor/layers/modalities.py
- tensor2tensor/layers/transformer_layers.py
- tensor2tensor/models/__init__.py
- tensor2tensor/models/transformer.py
- tensor2tensor/utils/modality.py
- tensor2tensor/utils/optimize.py
- tensor2tensor/utils/quantization.py
- tensor2tensor/utils/t2t_model.py
Hi T2T team,
This is a first-pass attempt at providing mixed-precision support to Transformer on tensor2tensor.  Per discussion on gitter with @lukaszkaiser, this branch does *not* yet achieve all the speedups we expect, but he suggested we put up this branch and perhaps the t2t team will see something subtle (or obvious...) that we missed and we can all get performance where it should be, and merge strong mixed precision support into t2t.
* We have been gradually trying to replicate the results of fairseq’s “Scaling Neural Machine Translation”, https://arxiv.org/abs/1806.00187.  This paper demonstrates increased training speed (both wall clock and fundamental efficiency) on transformer translation through mixed precision and some other tricks.  Table 1 is the core result. (Trying to …
> Mixed Precision Support for Transformer

- tensor2tensor/rl/envs/simulated_batch_env.py
This is to make debug videos more diverse, as env 0 will start at the beginning of the episode,
when flag simulation_flip_first_random_for_beginning is present.
> Using last env for debug movies.

- floyd.yml
FloydHub now has [support for TensorFlow 1.12](https://docs.floydhub.com/guides/tensorflow/#tensorflow-112) which is require for T2T to work correctly.
> Use TensorFlow 1.12 image on FloydHub

- tensor2tensor/utils/cloud_mlengine.py
This prints useful information on how to interact with the submitted job via the command line.
Example output:
```
INFO:tensorflow:Launched shake_shake_image_mnist_t2t_20190121_123909. See console to track: https://console.cloud.google.com/mlengine/jobs/.
INFO:tensorflow:Interact with the training job from the command line:
INFO:tensorflow:Abort job: gcloud ml-engine jobs cancel shake_shake_image_mnist_t2t_20190121_123909
INFO:tensorflow:Stream logs: gcloud ml-engine jobs stream-logs shake_shake_image_mnist_t2t_20190121_123909
INFO:tensorflow:Open tensorboard: tensorboard --logdir gs://lgeiger-test-bucket/training-test
```
> ML Engine: Improve logging

- docs/multi_problem.md
vis. issue https://github.com/tensorflow/tensor2tensor/issues/1394
> First draft of multi-problem docs

- tensor2tensor/data_generators/problem.py
[E**rror Querying Server: Requested more than 0 entries, but params is empty**.](https://github.com/tensorflow/tensor2tensor/issues/1219) #1219
After days of work, I have solved this problem. It caused by the function serving_input_fn. The input example no need to be reversed any more. So I deleted the code.
> sovle the issue 1219. When use the translate_enzh_rev problem module, the decoding resulte is wrong.

- tensor2tensor/models/research/universal_transformer.py
We need universal_transformer_base to have a similar capacity to transformer_base, which means, we need a larger size for the hidden states since there is a single layer in UT. Using transformer_big hparams, we had a UT with an approximately similar number of trainable parameters to transformer_base. 
Apparently, [the default batch size in transformer_big has been reduced to 2048 from 4096 to be able to train the model on a GPU  with 12 GB memory](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L1576), while we don't want this change in universal_transformer_base. In order to have the same setup we use in the paper (```batch_size = 4096```), I change the universal_transformer_base to use transformer_base hparams instead of …
> Rewrites universal_transformer_base based on transformer_base

- tensor2tensor/utils/optimize.py
- tensor2tensor/utils/registry.py
Added optimizer registration, similar to other registration methods. This allows users to add new optimizers in their `t2t_usr_dir` without having to manipulate tensor2tensor code directly.
EDIT: points below [resolved](https://github.com/tensorflow/tensor2tensor/pull/1401/commits/4d1b88f9842a099b2d4f02ecb8548d74bacabcd9)
Error checking number of args in registered function is a bit gross (`inspect` doesn't play nicely with `functools.partial`), but unsure of a better way of handling this.
I'm not convinced the way of handling optimizers in `tf.contrib.layers.OPTIMIZER_CLS_NAMES` is optimal, but I don't have a better way to bind loop variables to function calls.
> added optimizer registry

- README.md
- docs/walkthrough.md
Hi,
thanks for integrating the Evolved Transformer into `tensor2tensor` (f7c64216cb3013331e45dbc35b51f79010370b3e and 9626aff2f5b9ce9ca03aa576811af550e3c5ccff) :heart: 
This PR adds the [relevant paper](https://arxiv.org/abs/1901.11117) to the doc section.
> Add evolved transformer paper

- tensor2tensor/data_generators/wiki_revision_utils.py
- tensor2tensor/layers/common_attention.py
- tensor2tensor/layers/common_layers.py
- tensor2tensor/layers/discretization.py
- tensor2tensor/models/research/autoencoders.py
- tensor2tensor/models/research/cycle_gan.py
This PR replaces `log(1 + x)` with `log1p(x)` and `exp(x) - 1` with `expm1(x)`. These functions are more precise if x is close to zero.
> Replace numerically more stable log1p and expm1

- tensor2tensor/data_generators/cipher.py
- tensor2tensor/data_generators/text_encoder.py
- tensor2tensor/data_generators/wiki_revision_utils.py
- tensor2tensor/layers/common_layers.py
- tensor2tensor/rl/trainer_model_based.py
- tensor2tensor/serving/serving_utils.py
Just some minor readability improvements that accumulated during debugging bugs in my custom model code.
> Slightly simplify python loops and attr access

- tensor2tensor/data_generators/audio.py
- tensor2tensor/data_generators/gym_env.py
- tensor2tensor/data_generators/gym_env_test.py
- tensor2tensor/data_generators/librispeech.py
- tensor2tensor/data_generators/mscoco.py
- tensor2tensor/models/research/attention_lm_moe.py
- tensor2tensor/rl/player_utils.py
- tensor2tensor/utils/hparam.py
- tensor2tensor/utils/metrics.py
- tensor2tensor/utils/rouge.py
- tensor2tensor/utils/t2t_model.py
This is just some search and replace to improve readability:
- `d = dict()` --> `d = {}`
- `l = list()` --> `l = []`
Some nice benefit of this is that literals in Python are quite a bit faster (though only 60 ns - 75 ns):
```shell
In [1]: %timeit d = dict()
101 ns ± 0.0829 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [2]: %timeit dl = {}
34.1 ns ± 0.378 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [3]: %timeit l = list()
101 ns ± 0.541 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [4]: %timeit l = []
25.4 ns ± 0.346 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
> Prefer literals over list and dict functions

- tensor2tensor/data_generators/mscoco.py
After trying to run tensor2tensor on COCO dataset, I got error:
```
Traceback (most recent call last):
[...]
File "/root/.local/lib/python3.5/site-packages/tensor2tensor/bin/t2t_trainer.py", line 401, in <module>
tf.app.run()
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
_sys.exit(main(argv))
File "/root/.local/lib/python3.5/site-packages/tensor2tensor/bin/t2t_trainer.py", line 384, in main
generate_data()
File "/root/.local/lib/python3.5/site-packages/tensor2tensor/bin/t2t_trainer.py", line 279, in generate_data
registry.problem(problem_name).generate_data(data_dir, tmp_dir)
File "/root/.local/lib/python3.5/site-packages/tensor2tensor/data_generators/image_utils.py", line 372, in generate_data
self.dev_filepaths(data_dir, …
```
> [bugfix] - COCO dataset reads images as text files

- tensor2tensor/data_generators/cnn_dailymail.py
- tensor2tensor/data_generators/multi_problem_v2.py
- tensor2tensor/data_generators/video_utils.py
- tensor2tensor/envs/env_problem.py
- tensor2tensor/insights/server.py
- tensor2tensor/layers/discretization.py
- tensor2tensor/layers/vq_discrete.py
- tensor2tensor/models/video/base.py
- tensor2tensor/rl/player.py
- tensor2tensor/utils/data_reader.py
- tensor2tensor/visualization/attention.py
This PR replaces loops that only append to a list with list comprehensions. This makes it more concise and (arguably) more readably.
List comprehensions also are quite a bit faster than appending to a list. Toy example in Python 3.6:
```python
In [1]: %%timeit
...: l = []
...: for i in range(5000):
...:     l.append(i)
375 µs ± 1.73 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
In [2]: %%timeit
...: l = [i for i in range(5000)]
168 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
> Replace .append loop with list comprehension

- tensor2tensor/data_generators/all_problems.py
- tensor2tensor/data_generators/generator_utils.py
- tensor2tensor/data_generators/transduction_problems.py
- tensor2tensor/models/research/vqa_self_attention.py
T2T uses a mix of `xrange` and `range` leading to Python 3 errors when `xrange` isn't imported from `six.moves`.
This PR switches all usage of `xrange` to `six.moves.range` which is equivalent and supports both Python 3 and 2.
> Use xrange from six to fix Python 3 support

- tensor2tensor/bin/t2t_decoder.py
Update t2t_decoder.py to pass in checkpoint_path FLAG correctly in decode_from_dataset
> t2t_decoder checkpoint_path fix

- tensor2tensor/utils/decoding.py
This fixes a bug introduced in https://github.com/tensorflow/tensor2tensor/commit/47ced4eecd13974e3a690a80b1f60effda089fa9
Fix step size extraction for checkpoint name with - in it such as avg-model.ckpt-1234
> Fix step size extraction for checkpoint name 

- tensor2tensor/serving/query.py
- tensor2tensor/serving/serving_utils.py
When I serve a transformer seq2se2 model exprted with decode_hparams `return_beams=True`, the decoding process of t2t-query-server raised an error:
```
Traceback (most recent call last):
File "/home/uuuzzz/anaconda3/envs/tensor2tensor/bin/t2t-query-server", line 4, in <module>
__import__('pkg_resources').run_script('tensor2tensor==1.10.0', 't2t-query-server')
File "/home/uuuzzz/anaconda3/envs/tensor2tensor/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/home/uuuzzz/anaconda3/envs/tensor2tensor/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
exec(code, namespace, namespace)
File "/home/uuuzzz/anaconda3/envs/tensor2tensor/lib/python3.6/site-packages/tensor2tensor-1.10 …
```
> Modify serving utils

- tensor2tensor/data_generators/wikisum/parallel_launch.py
- tensor2tensor/utils/cloud_mlengine.py
This PR upgrades the ML Engine runtime to 1.13 in order to fix #1472. Unfortunately ML Engine doesn't support TPUs in version 1.13 yet: https://cloud.google.com/ml-engine/docs/release-notes
This also removes the unused Gcloud class to clean up the code a bit.
> Upgrade ML Engine runtime to 1.13 and remove unused Gcloud class

- tensor2tensor/data_generators/problem.py
new `Problem` property `all_metrics_fns` allows extending metrics functions in a `Problem` versus adding it to `metrics.METRICS_FNS`, especially if the function depends on problem information
> extensibility for eval metrics

- tensor2tensor/utils/t2t_model.py
I was training a transformer model with a real-value output. I had my problems file set up properly, but when using `.infer` to load a trained model checkpoint and use it to run inference on some input, I was getting very obscure errors to do with tensor sizes. After some debugging it became apparent that the tensor2tensor framework was trying to look for a class to output, and did not accept that I wanted a real-valued output.
Turns out this is due to a small typo in t2t_model - when checking if the output modality is real, it decided it was not and this caused the decoder part of the library to use fast_decode rather than the slow version that seems suitable for real valued predictions. It checks if the output modality name begins with "Real_" to determine this.
Unfortunately, the name …
> Fixed bug in _target_modality_is_real

- docs/new_model.md
I've written docs that were marked as TODO for a long time. 
Most of them are copied from appropriate places in the repository, but I think for someone who just starts with t2t it will be easier having it all in one place.
Also I've changed Contributions link to absolute one since it was 404'ing from docs directory.
> Documentation for creating own model

- tensor2tensor/layers/discretization.py
This fixes the semantic hashing bug mentioned here https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/research/transformer_vae.py#L870
@dustinvtran, @lukaszkaiser is this the correct way to fix this bug?
> Adding extra linear to semantic hashing discretization bottleneck.

- tensor2tensor/models/transformer.py
This pull request enables using `partial_targets` field of the inputs dictionary at inference time, when `inputs` field is also specified.
One of the cases when partial targets are useful is mutilingual speech recognition problem, as described in this paper: [Multilingual End-to-End Speech Recognition with A Single Transformer on Low-Resource Languages](https://arxiv.org/abs/1806.05059). Language tags may be specified at `partial_targets` input, if there is prior knowledge of the speaker's language.
> Using partial targets at inference time.

- tensor2tensor/data_generators/algorithmic_math_deepmind.py
The url to the math dataset got updated.
Reference: https://github.com/deepmind/mathematics_dataset/issues/2
> Updated link to DeepMind Math dataset

- tensor2tensor/models/research/rl.py
- tensor2tensor/rl/dopamine_connector.py
- tensor2tensor/rl/trainer_model_based_params.py
Parameters set for rlmb with Rainbow -  "rlmb_dqn_guess1_rainbow"
Note that there is a lot of common code between Rainbow and VanillaDQN. Most likely we want
to remove Vanilla DQN and only have Rainbow if experiments will confirm that the latter works. If we want to keep both Vanilla DQN and Rainbow, larger refactor is required. I left TODO for this in dopamine_connector.py
> Model Based RL: Introduce Rainbow.

- tensor2tensor/models/transformer.py
Sometimes, attention weights may be useful for explaining model's results, visualization, etc. At speech recognition, encoder-decoder attention may be used for time alignment of waveform with recognized phonemes. In old releases, or without fast decoding, the attention is stored at `attention_weights`, but it has been broken at fast decoding mode: #898 ,  #917 .
This PR returns weights in `cache["attention_history"]`, works in both Eager and Graph modes.
> Storing encoder-decoder attention history at Transformer's cache during fast decoding.

- tensor2tensor/utils/expert_utils.py
In the case of topk gating, the loss is falsely multiplied twice by the loss coefficient.
> Loss twice multiplied with loss_coef

- README.md
- docs/index.md
- tensor2tensor/data_generators/translate_enes.py
Hi!
I was able to successfully add and use a English-Spanish translation problem, using **Common Crawl**, **EuroParl v7**, **UN Corpus** and **ParaCrawl** as my datasets.
I trained both an EN-ES and an ES-EN Transformer models (using the `transformer_big_single_gpu` hyperparameters set) with this new problem specification.
> Add English-Spanish translation problem

- tensor2tensor/utils/optimize.py
Automatic Mixed Precision for Tensorflow has been recently introduced:
https://medium.com/tensorflow/automatic-mixed-precision-in-tensorflow-for-faster-ai-training-on-nvidia-gpus-6033234b2540
This PR adds automatic mixed precision training to all tensor2tensor models via setting a single OS flag:
```
export TF_ENABLE_AUTO_MIXED_PRECISION=1
```
Alternatively, it can also be enabled by directly calling the optimize() function with an appropriate parameter:
```
optimize(loss, learning_rate, hparams, use_tpu=False, variables=None, gpu_auto_mixed_precision=True)
```
Automatic (GPU) mixed precision should not be used with TPU and manual mixed precision. The PR checks for these cases.
We've tested speed impact on several models on 1x V100 16GB GPU:
Image classification - Resnet-50: 1.9x …
> Adding automatic mixed precision support

- tensor2tensor/utils/beam_search.py
Maybe _is_not_finished is more proper name for cond function because tf.while_loop keeps running while cond is True.
> Change confusing function name

- tensor2tensor/bin/t2t_trainer.py
- tensor2tensor/layers/common_hparams.py
- tensor2tensor/utils/optimize.py
In continuation of  https://github.com/tensorflow/tensor2tensor/pull/1637 and in response to @afrozenator 's comments in https://github.com/tensorflow/tensor2tensor/pull/1680
In this PR, we re-organize automatic mixed precision training support to provide a cleaner implementation and an easier interface via using hyper parameters. 
In particular, [GPU automatic mixed precision training](https://medium.com/tensorflow/automatic-mixed-precision-in-tensorflow-for-faster-ai-training-on-nvidia-gpus-6033234b2540) can now be enabled via setting a flag (and correspondingly a so-named hyper-parameter) `gpu_automatic_mixed_precision` for **all tensor2tensor models**, for example: 
**Transformer**
```
PROBLEM=translate_ende_wmt32k
MODEL=transformer
HPARAMS=transformer_big …
```
> Refine automatic mixed precision support via hyper param

- tensor2tensor/serving/serving_utils.py
When we use `t2t-query-server` and `TensorFlow Serving` is hosted by our own(gRPC), the responses are from `TensorFlow Serving` converted to `ndarray`.
https://github.com/tensorflow/tensor2tensor/blob/8a95e96f31d1beccb8efbb2290f6a271600eb3f3/tensor2tensor/serving/serving_utils.py#L116-L123
But when we use it with Cloud ML Engine, the responses are not converted.
https://github.com/tensorflow/tensor2tensor/blob/8a95e96f31d1beccb8efbb2290f6a271600eb3f3/tensor2tensor/serving/serving_utils.py#L143-L144
then, got error,
```bash
Traceback (most recent call last):
File "//anaconda3/envs/py27/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "//anaconda3/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1951, in …
```
> Fix serving response from Cloud ML Engine

- tensor2tensor/data_generators/translate_enid.py
Change to untokenized parallel corpora due to t2t automatically tokenizes sentences.
> En-Id untokenized parallel corpora

- tensor2tensor/data_generators/text_problems.py
- tensor2tensor/data_generators/text_problems_test.py
- tensor2tensor/models/transformer.py
- tensor2tensor/utils/t2t_model.py
A variety of NLP problems involve training regression models to predict continuous-valued ratings from text (e.g., sentiment scoring). While T2T supports several `REAL` modalities, there is no base class for regression-based text problems. This PR introduces a `Text2RealProblem` that is analogous to the existing `Text2ClassProblem`, but for regression problems.
The class also supports multitask regression via the `ntasks` property, which allows for the regression target to be an n-dimensional float vector.
Note that this PR doesn't contribute any additional problems to the registry (for now), since the datasets I've been training on are not public. That said, this base class makes it very straightforward to define a custom text regression problem, and I hope that it will be useful for …
> Create Text2RealProblem class for regression-based problems

- tensor2tensor/utils/cloud_mlengine.py
Updated the runtime version to 1.14 and added support for
using V100 GPUs on Cloud ML.
Test plan:
I ran several jobs with a custom problem definition on Cloud ML using each machine type (P100 and V100, medium and large) to make sure they worked.
> Add support for training on V100 GPUs on Cloud ML

- tensor2tensor/utils/t2t_model.py
In T2TModel.infer, the comment mentioned that the returned outputs tensor has a shape of `[batch_size, <= decode_length] if beam_size == 1`, but this is wrong. It should be: `if top_beams == 1`. It is a simple mistake but it may really confuse a beginner (like me).
> Fixed a mistake in a doc comment

- tensor2tensor/models/research/glow_ops.py
since,
1. scaled_time is calculated by `scaled_time = tf.expand_dims(position, 1) * tf.expand_dims(inv_timescales, 0)`, while position_idx in position will **start by 0**.
2. scaled_time will be used to calculate position embedding by `signal = tf.concat([tf.sin(scaled_time), tf.cos(scaled_time)], axis=1)`
Thus, position_embedding of first token will always be combined with half zeros and half ones.
But the purpose of addding timing pos_embed should be helping model to learn relative and absolute position information between words by triangle relations of these words, i.e. sin(\alpha+\beta)=sin(\alpha)cos(\beta)+sin(\beta)cos(\alpha).
> inaccurate calculation of first_token's pos_embedding

- tensor2tensor/utils/decoding.py
Originally the decode length is hard-coded in the `decoding.py`. 
I believe that is a bug because the `extra_length` set in `decode_hp` should be used as the `decode_length` rather than the original `tf.shape(x)[1] + 50`, referring to the usage of `features['decode_length']` in the followings:
https://github.com/tensorflow/tensor2tensor/blob/8107e53e8d8896c521522e9335a266b4b7510c37/tensor2tensor/utils/t2t_model.py#L932-L933 https://github.com/tensorflow/tensor2tensor/blob/8107e53e8d8896c521522e9335a266b4b7510c37/tensor2tensor/models/transformer.py#L712-L713
> Fix the decode_length for decoding

- tensor2tensor/models/__init__.py
- tensor2tensor/models/research/shuffle_network.py
Added Neural Shuffle-Exchange model for Seq2Seq problems as described in [paper](https://papers.nips.cc/paper/8889-neural-shuffle-exchange-networks-sequence-processing-in-on-log-n-time) and [original code](https://github.com/LUMII-Syslab/shuffle-exchange).
> Neural Shuffle-Exchange Seq2Seq model

- tensor2tensor/models/research/shuffle_network.py
When target dimensions are not known, use hparams.max_length. max_length should be a power of 2.
Max length can be enforced using hparams.force_max_length=True.
Auto-Regressive decoding not supported at this moment.
> Inference support for Neural Shuffle-Exchange network

- tensor2tensor/utils/trainer_lib.py
When initializing TPU training with create_run_config, it is currently not possible to select a TPU zone different from the zone of the GCP virtual machine, assumed by TPUClusterResolver.
This pull request only adds one parameter in order to select a different TPU zone.
> Add option to select a different TPU zone in create_run_config

- tensor2tensor/layers/common_layers.py
- tensor2tensor/models/__init__.py
- tensor2tensor/models/research/residual_shuffle_exchange.py
T2T  implementation of the Residual Shuffle-Exchange network.
Paper: https://arxiv.org/abs/2004.04662
Original code: https://github.com/LUMII-Syslab/RSE
> Residual Shuffle-Exchange network
