tensorflow/tensor2tensor

- tensor2tensor/data_generators/algorithmic_math.py
[Issue #47](https://github.com/tensorflow/tensor2tensor/issues/47)
> due to https://github.com/tensorflow/tensor2tensor/issues/47

- tensor2tensor/bin/t2t-datagen
- tensor2tensor/data_generators/problem_hparams.py
- tensor2tensor/data_generators/ptb.py
- tensor2tensor/data_generators/text_encoder.py
Would like to run PTB benchmark using the `attention_lm`.
I added PTB download & generators. Things about problems_hyperparams and t2t_datagen are not super clear to me, I maybe made mistakes. 
Added a way to work with unknown tokens in `TokenTextEncoder` as well.
> Penn TreeBank dataset for language modeling 

- tensor2tensor/models/common_layers.py
- tensor2tensor/utils/data_reader.py
* Pad 4 pixels of 0s on each side
* Randomly crop 32x32
* Randomly mirror vertically
Is there a good way to make this optional?
> Add image augmentation for CIFAR-10

- tensor2tensor/data_generators/text_encoder.py
- tensor2tensor/data_generators/tokenizer_test.py
Added import of six.unichr on files using unichr for python3.
> importing six.unichr

- tensor2tensor/models/common_hparams.py
- tensor2tensor/utils/trainer_utils.py
- tensor2tensor/utils/yellowfin.py
- tensor2tensor/utils/yellowfin_test.py
I have adapted [YellowFin](https://github.com/JianGoForIt/YellowFin) to be usable within `T2T` and to be `Tf.train.Optimizer` "compliant", but unfortunately a possible error/TF bug does not ensure the smooth running of the Optimizer. The Optimizer is far to be "production-ready" and there will be different improvements to be done such as multi-GPU testing, code readability and TF integration. This PR is in request of #125 .
> Integrate YellowFin Optimizer(with test) in T2T

- tensor2tensor/bin/t2t-datagen
- tensor2tensor/data_generators/algorithmic.py
- tensor2tensor/data_generators/problem.py
- tensor2tensor/data_generators/wmt.py
To make use of argument FLAGS.num_shards
> Add 'num_shards" to generate_data 

- tensor2tensor/data_generators/algorithmic_cipher.py
- tensor2tensor/data_generators/all_problems.py
- tensor2tensor/data_generators/cipher.py
Adds a simple shift cipher and vigenere cipher on synthetically sampled data.
> Algorithmic Shift and Vigenere Cipher Data Generator

- README.md
Hi,
with release 1.1.9 the problem names changed for the WMT task, so this PR updates the Walkthrough section in `README.md`.
> doc: update problem name for wmt task

- docs/new_problem.md
I don't want to step on anyone's toes, but I think this cleanup of new_problem.md would be a lot easier for new users to understand (no unused imports, consistent class references, etc.) It's a great guide otherwise!
> Clean up of new_problem.md

- tensor2tensor/layers/common_attention.py
Also serving as a test of Travis CI build. 
PiperOrigin-RevId: 168170097
> Added an assert in common_attention.

- tensor2tensor/data_generators/cnn_dailymail.py
> Fixing #359: decoding str object instead of bytes

- tensor2tensor/data_generators/cnn_dailymail.py
Adding the CNN/Dailymail summarization problem: Summarize news articles to their respective story highlights.
> CNN/Dailymail Summarization

- docs/new_problem.md
* Added some instructions for using pip to create editable install so you can locally test. 
* Also added commands to run the local test.
* Fixed bug with accidental `self` argument in hparams definition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tensor2tensor/490)
> Add helpful (I think) instructions & bugfix

- tensor2tensor/utils/bleu_hook.py
- tensor2tensor/utils/bleu_hook_test.py
> fix and test bleu_hook.bleu_tokenize

- tensor2tensor/bin/t2t_trainer.py
The hparams file will now be more human readable and keys will be sorted
> Pretty print and sort Hparams

- tensor2tensor/models/research/rl.py
- tensor2tensor/rl/README.md
- tensor2tensor/rl/collect.py
- tensor2tensor/rl/envs/utils.py
- tensor2tensor/rl/ppo.py
- tensor2tensor/rl/rl_trainer_lib.py
- tensor2tensor/rl/rl_trainer_lib_test.py
- evaluation runs (including generating videos),
- additional summaries,
- bug fixes.
> Further improvements to rl

- tensor2tensor/data_generators/generator_utils.py
range returns a generator in Python3, but we need list here
> fix packed problems for Python3

- README.md
- docs/distributed_training.md
- docs/index.md
- tensor2tensor/models/lstm.py
Some minor documentation fixes are introduced with this PR :)
> Minor documentation fixes

- tensor2tensor/data_generators/all_problems.py
With this PR the English-Vietnamese (`translate_envi`) problem is added to all problems. I accidentally missed that in #611.
> problem: add translate_envi to all problems

- tensor2tensor/utils/bleu_hook.py
- tensor2tensor/utils/rouge.py
- tensor2tensor/utils/t2t_model.py
Address issue #650, where a single eval metric was returned per evaluation
> Fix evaluation bug and a few minor things (spelling, broken links)

- tensor2tensor/utils/get_ende_bleu.sh
This PR is to fix a minor bug in utils/get_ende_bleu.sh.
> fixed minor bug in get_ende_bleu.sh

- .gitignore
- tensor2tensor/utils/beam_search.py
without that change below, for language model problem, when use batch predict, all samples in the batch will end up with the same result after get topk in method grow_topk()
> grow topk reshape issue

- README.md
- docs/walkthrough.md
- tensor2tensor/utils/adafactor.py
Hi,
I read something about adafactor on [Twitter](https://twitter.com/jekbradbury/status/985673409450278912), so this PR adds the recently published paper "Adafactor: Adaptive Learning Rates with Sublinear Memory Cost" on arxiv to the paper section.
> Add adafactor paper

- docs/distributed_training.md
> Add note about output_dir

- tensor2tensor/bin/t2t_trainer.py
- tensor2tensor/utils/trainer_lib.py
Control the display steps when running `Experiment`.
> add log_step_count_steps argument

- tensor2tensor/data_generators/gh_function_docstring_encoder.py
> Github Function-Docstring Similarity Encoder

- tensor2tensor/data_generators/gym_problems.py
- tensor2tensor/rl/envs/simulated_batch_env.py
- tensor2tensor/rl/envs/tf_atari_wrappers.py
- tensor2tensor/rl/model_rl_experiment.py
Some fixes of eval code and improvements
> Eval reimplmentations

- README.md
- docs/walkthrough.md
- tensor2tensor/models/research/universal_transformer.py
Hi,
finally, the [universal transformers](https://arxiv.org/abs/1807.03819) paper is out :heart: 
This PR adds the paper to the main documentation.
> Add universal transformer paper

- tensor2tensor/utils/optimize.py
Removed note about re-scaling the lr with Adam.
I believe this is a legacy of the old way LR+Adam was handled and that the docs weren't updated when the code was updated.
Pushing a PR because this is confusing to read now.  :)  (Unless I'm wrong!)
> minor docs fix to adam

- tensor2tensor/data_generators/style_transfer.py
- tensor2tensor/data_generators/style_transfer_test.py
PR changes:
1. fixed bug with generating data for 'original english to modern one' problem,
2. added char-based style transfer problems,
3. added unit tests.
> fixed bug with data_gen in style transfer problem

- tensor2tensor/utils/t2t_model.py
some minor change in beam_decode_slow
> beam decode slow

- tensor2tensor/utils/get_rouge.py
Fixed a typo mentioned in https://github.com/tensorflow/tensor2tensor/issues/968
> typo fixed from tf.logging.into to tf.logging.info

- setup.py
- tensor2tensor/data_generators/all_problems.py
- tensor2tensor/data_generators/paraphrase_ms_coco.py
- tensor2tensor/data_generators/paraphrase_ms_coco_test.py
PR content:
Added new generic problem for paraphrase generation:
Model input: Paraphrase#1
Model output: Paraphrase#2
Additionally, MS COCO corpus with captions was used for the specific implementation of this problem.
> added paraphrase generation problem

- docs/cloud_mlengine.md
- docs/cloud_tpu.md
- docs/distributed_training.md
Hi,
nothing special, but this PR introduces some markdown and hyperlink fixes :)
> Minor doc fixes

- tensor2tensor/models/research/universal_transformer_util.py
This was identified (not by me) in https://github.com/tensorflow/tensor2tensor/issues/1004.
Putting in a PR to ensure this is fixed.
If this is not a correct fix, then the underlying code needs to be rejiggered for readability...
> Fix to universal transformer update weights

- tensor2tensor/data_generators/audio_encoder.py
- tensor2tensor/data_generators/librispeech.py
- tensor2tensor/data_generators/speech_recognition.py
Small refactor in speech models.
1. Moved AudioEncoder to the separate script audio_encoder (similar to text_encoders).
2. Added tqdm for minitoring input audio files preprocessing in Librispeech problem.
> small refactor in speech problems

- tensor2tensor/rl/trainer_model_based.py
Adding short ppo training on real env between epochs
> Adding short ppo training on real env between epochs

- tensor2tensor/data_generators/gym_problems.py
- tensor2tensor/rl/collect.py
- tensor2tensor/rl/envs/batch_env_factory.py
- tensor2tensor/rl/rl_trainer_lib.py
- tensor2tensor/rl/rl_trainer_lib_test.py
- tensor2tensor/rl/trainer_model_based.py
> Ppo eval 2

- tensor2tensor/data_generators/gym_env.py
- tensor2tensor/data_generators/gym_env_test.py
Model-Based RL; T2TEnv, T2TEnvGym; Observation preprocessing, saving unclipped rewards, tests. 
Continuation to [pull request 1123](https://github.com/tensorflow/tensor2tensor/pull/1123)
> Preprocessing in t2 t gym env

- tensor2tensor/data_generators/gym_env.py
- tensor2tensor/data_generators/gym_env_test.py
- tensor2tensor/data_generators/gym_problems.py
- tensor2tensor/data_generators/problem.py
- tensor2tensor/rl/envs/batch_env_factory.py
- tensor2tensor/rl/trainer_model_based_new.py
Enable restarting MB RL pipeline.
> Model-Based RL: Data loading, restarting experiments

- tensor2tensor/data_generators/translate_entn.py
Hi!
Got some interesting results for the following low-resourced language if anyone is interested.
With this PR a new problem is added: English-[Setswana](https://en.wikipedia.org/wiki/Tswana_language) using the [Autshumato English-Sestwana Parallel Corpus](https://rma.nwu.ac.za/index.php/resource-catalogue/autshumato-english-setswana-multi-bilingual-corpus.html).
I trained an English to Sestwana Transformer model for 125k steps on a NVIDIA K80 GPU.
Here are comparisons of BLEU score:
| Model                    | BLEU  |
|--------------------------|-------|
| [Phrase-based Translation](http://researchspace.csir.co.za/dspace/bitstream/handle/10204/6409/De%20Waal_2012.pdf?sequence=1#page=123) | 28.8  |
| Convolutional Seq2Seq              | 27.77 |
| Transformer (uncased)    | 33.53 |
| …
> Added English-Setswana translation problem

- tensor2tensor/layers/modalities.py
It gives troubles to beginners like me. After checked code in t2t_model.py, I find out this description about function returns is wrong.
> Fix a bug in document

- tensor2tensor/layers/bayes.py
- tensor2tensor/layers/bayes_test.py
@markvdw @dusenberrymw: Can you two review the pull request?
cc'ing for interest: @danijar @sguada @dmrd @agane @murphyk
Nothing is set in stone, so I'm open to thoughts on both API and implementation. Some limitations for simplicity:
+ Inputs must have 1-D batch dimension, not unlike most Keras layers.
+ There is only one numerical stability trick, which is perturbing the diagonals by epsilon before any calls to tf.cholesky. Any performance / numerical tips are welcome.
To implement ExponentiatedQuadratic, I copied Edward1's implementation (http://edwardlib.org/api/ed/rbf; https://github.com/blei-lab/edward/pull/596), and which is based on GPflow's.
> Add GaussianProcess layer.

- tensor2tensor/utils/t2t_model.py
> Fix Python 3 compatibility issue with self_generated_targets

- tensor2tensor/models/video/base_vae.py
> Fixing decode for extra output frames.

- tensor2tensor/rl/evaluator.py
- tensor2tensor/rl/rl_utils.py
(consists commit from https://github.com/tensorflow/tensor2tensor/pull/1396 )
> Model-Based RL: Planner hparams, first guess

- .travis.yml
- oss_scripts/oss_pip_install.sh
> CI: Test tf-nighly on Python 3 and cleanup config to speedup test

- tensor2tensor/data_generators/all_problems.py
- tensor2tensor/data_generators/yelp_full.py
- tensor2tensor/data_generators/yelp_polarity.py
I added yelp_review dataset including Yelp_review_full and yelp_review_polarity,  which is proposed by Xiang Zhang in [Paper](https://arxiv.org/abs/1509.01626) **Character-level Convolutional Networks for Text Classification** .
> Add Yelp_Review Dataset

- tensor2tensor/rl/trainer_model_based_params.py
Can be run with e.g
python -m tensor2tensor.rl.trainer_model_based \
--loop_hparams_set=rlmb_base_stochastic_discrete_sticky_actions \
--loop_hparams=game=pong \
--output_dir ~/t2t_train/mb_sd_pong
Which is equivalent to using loop_hparams_set=rlmb_base_stochastic_discrete and adding sticky_actions=True to loop_hparams.
> Parameter set for sticky actions.

- tensor2tensor/visualization/visualization.py
decode function used input vocab instead of target vocab.
> fix decode bug

- tensor2tensor/layers/common_attention.py
add `save_weights_to` for `dot_product_unmasked_relative_v2` and `dot_product_relative_v2`
> save attention weights for relative attention v2

- tensor2tensor/layers/common_layers.py
Hi, 
I added minor modification for deep_discriminator, described in issue: https://github.com/tensorflow/tensor2tensor/issues/1678
> deep_discriminator - missed relu

- tensor2tensor/models/research/universal_transformer.py
- tensor2tensor/models/transformer.py
- tensor2tensor/utils/decoding.py
Reverts tensorflow/tensor2tensor#1726
> Revert "Fix decoding in prepend mode"

- tensor2tensor/models/research/universal_transformer.py
- tensor2tensor/models/transformer.py
- tensor2tensor/utils/decoding.py
Reverts tensorflow/tensor2tensor#1749
> Revert "Revert "Fix decoding in prepend mode""

- tensor2tensor/data_generators/all_problems.py
- tensor2tensor/data_generators/translate_encs_cubbitt.py
This code should serve as a reference (to be cited in a paper),
so I would prefer to have it in a (single) separate file.
> add a backtranslation-based en-cs NMT problem and hparams
